---
title: Itakda ang istilo ng pag-ikot ng sprite
hero_image: mga imahe / banner.png
description: Itakda ang istilo ng pag-ikot ng isang sprite
listed: false
copyedit: true
steps:
  - 
    title: Panimula
