---
title: Establecer el estilo de rotación de objetos
hero_image: images/banner.png
description: Establecer el estilo de rotación de un objeto
listed: false
copyedit: true
steps:
  - title: Introducción
