---
title: Setarea modului de rotire al personajului
hero_image: images/banner.png
description: Setează modul de rotire al personajului
listed: false
copyedit: true
steps:
  - 
    title: Introducere
