---
title: Establece el estilo de rotación del objeto
hero_image: images/banner.png
description: Establece el estilo de rotación de un objeto
listed: false
copyedit: true
steps:
  - 
    title: Introducción
