---
title: Impostare lo stile di rotazione di uno sprite
hero_image: images/banner.png
description: Imposta lo stile di rotazione di uno sprite
listed: false
copyedit: true
steps:
  - title: Introduzione
